import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

String arabicFont = "quran";
double arabicFontSize = 28;
double mushafFontSize = 40;
Color color = Color(0xFF672CBC);
Uri quranAppUri = Uri.parse('');

TextStyle ayahStyle = const TextStyle(fontFamily: 'HafsQuran', fontSize: 24);
Future saveSetting() async {
  final prefs = await SharedPreferences.getInstance();
  await prefs.setInt('arabicFontSize', arabicFontSize.toInt());
  await prefs.setInt('mushafFontSize', mushafFontSize.toInt());
}

Future getSetting() async {
  try {
    arabicFontSize = 28;
    mushafFontSize = 40;
    final prefs = await SharedPreferences.getInstance();
    arabicFontSize = await prefs.getInt('arabicFontSize')!.toDouble();
    mushafFontSize = await prefs.getInt('mushafFontSize')!.toDouble();
  } catch (_) {}
}

List<String> jozz = [
  'الأول',
  'الثاني',
  'الثالث',
  'الرابع',
  'الخامس',
  'السادس',
  'السابع',
  'الثامن',
  'التاسع',
  'العاشر',
  'الحادي عشر',
  'الثاني عشر',
  'الثالث عشر',
  'الرابع عشر',
  'الخامس عشر',
  'السادس عشر',
  'السابع عشر',
  'الثامن عشر',
  'التاسع عشر',
  'العشرون',
  'الواحد والعشرون',
  'الثاني والعشرون',
  'الثالث والعشرون',
  'الرابع والعشرون',
  'الخامس والعشرون',
  'السادس والعشرون',
  'السابع والعشرون',
  'الثامن والعشرون',
  'التاسع والعشرون',
  'الثلاثون',
];
List<Map> arabicSurahName = [
  {"surah": "1", "name": "الفاتحة", "revelationType": "مكية", "page": 1},
  {"surah": "2", "name": "البقرة", "revelationType": "مدنية", "page": 2},
  {"surah": "3", "name": "آل عمران", "revelationType": "مدنية", "page": 50},
  {"surah": "4", "name": "النساء", "revelationType": "مدنية", "page": 77},
  {"surah": "5", "name": "المائدة", "revelationType": "مدنية", "page": 106},
  {"surah": "6", "name": "الأنعام", "revelationType": "مكية", "page": 128},
  {"surah": "7", "name": "الأعراف", "revelationType": "مكية", "page": 151},
  {"surah": "8", "name": "الأنفال", "revelationType": "مدنية", "page": 177},
  {"surah": "9", "name": "التوبة", "revelationType": "مدنية", "page": 187},
  {"surah": "10", "name": "يونس", "revelationType": "مكية", "page": 208},
  {"surah": "11", "name": "هود", "revelationType": "مكية", "page": 221},
  {"surah": "12", "name": "يوسف", "revelationType": "مكية", "page": 235},
  {"surah": "13", "name": "الرعد", "revelationType": "مدنية", "page": 249},
  {"surah": "14", "name": "ابراهيم", "revelationType": "مكية", "page": 255},
  {"surah": "15", "name": "الحجر", "revelationType": "مكية", "page": 262},
  {"surah": "16", "name": "النحل", "revelationType": "مكية", "page": 267},
  {"surah": "17", "name": "الإسراء", "revelationType": "مكية", "page": 282},
  {"surah": "18", "name": "الكهف", "revelationType": "مكية", "page": 293},
  {"surah": "19", "name": "مريم", "revelationType": "مكية", "page": 305},
  {"surah": "20", "name": "طه", "revelationType": "مكية", "page": 312},
  {"surah": "21", "name": "الأنبياء", "revelationType": "مكية", "page": 322},
  {"surah": "22", "name": "الحج", "revelationType": "مدنية", "page": 332},
  {"surah": "23", "name": "المؤمنون", "revelationType": "مكية", "page": 342},
  {"surah": "24", "name": "النور", "revelationType": "مدنية", "page": 350},
  {"surah": "25", "name": "الفرقان", "revelationType": "مكية", "page": 359},
  {"surah": "26", "name": "الشعراء", "revelationType": "مكية", "page": 367},
  {"surah": "27", "name": "النمل", "revelationType": "مكية", "page": 377},
  {"surah": "28", "name": "القصص", "revelationType": "مكية", "page": 385},
  {"surah": "29", "name": "العنكبوت", "revelationType": "مكية", "page": 396},
  {"surah": "30", "name": "الروم", "revelationType": "مكية", "page": 404},
  {"surah": "31", "name": "لقمان", "revelationType": "مكية", "page": 411},
  {"surah": "32", "name": "السجدة", "revelationType": "مكية", "page": 415},
  {"surah": "33", "name": "الأحزاب", "revelationType": "مكية", "page": 418},
  {"surah": "34", "name": "سبإ", "revelationType": "مكية", "page": 428},
  {"surah": "35", "name": "فاطر", "revelationType": "مكية", "page": 434},
  {"surah": "36", "name": "يس", "revelationType": "مكية", "page": 440},
  {"surah": "37", "name": "الصافات", "revelationType": "مكية", "page": 446},
  {"surah": "38", "name": "ص", "revelationType": "مكية", "page": 453},
  {"surah": "39", "name": "الزمر", "revelationType": "مكية", "page": 458},
  {"surah": "40", "name": "غافر", "revelationType": "مكية", "page": 467},
  {"surah": "41", "name": "فصلت", "revelationType": "مكية", "page": 477},
  {"surah": "42", "name": "الشورى", "revelationType": "مكية", "page": 483},
  {"surah": "43", "name": "الزخرف", "revelationType": "مكية", "page": 489},
  {"surah": "44", "name": "الدخان", "revelationType": "مكية", "page": 496},
  {"surah": "45", "name": "الجاثية", "revelationType": "مكية", "page": 499},
  {"surah": "46", "name": "الأحقاف", "revelationType": "مكية", "page": 502},
  {"surah": "47", "name": "محمد", "revelationType": "مدنية", "page": 507},
  {"surah": "48", "name": "الفتح", "revelationType": "مدنية", "page": 511},
  {"surah": "49", "name": "الحجرات", "revelationType": "مدنية", "page": 515},
  {"surah": "50", "name": "ق", "revelationType": "مكية", "page": 518},
  {"surah": "51", "name": "الذاريات", "revelationType": "مكية", "page": 520},
  {"surah": "52", "name": "الطور", "revelationType": "مكية", "page": 523},
  {"surah": "53", "name": "النجم", "revelationType": "مكية", "page": 526},
  {"surah": "54", "name": "القمر", "revelationType": "مكية", "page": 528},
  {"surah": "55", "name": "الرحمن", "revelationType": "مدنية", "page": 531},
  {"surah": "56", "name": "الواقعة", "revelationType": "مكية", "page": 534},
  {"surah": "57", "name": "الحديد", "revelationType": "مدنية", "page": 537},
  {"surah": "58", "name": "المجادلة", "revelationType": "مدنية", "page": 542},
  {"surah": "59", "name": "الحشر", "revelationType": "مدنية", "page": 545},
  {"surah": "60", "name": "الممتحنة", "revelationType": "مدنية", "page": 549},
  {"surah": "61", "name": "الصف", "revelationType": "مدنية", "page": 551},
  {"surah": "62", "name": "الجمعة", "revelationType": "مدنية", "page": 553},
  {"surah": "63", "name": "المنافقون", "revelationType": "مدنية", "page": 554},
  {"surah": "64", "name": "التغابن", "revelationType": "مدنية", "page": 556},
  {"surah": "65", "name": "الطلاق", "revelationType": "مدنية", "page": 558},
  {"surah": "66", "name": "التحريم", "revelationType": "مدنية", "page": 560},
  {"surah": "67", "name": "الملك", "revelationType": "مكية", "page": 562},
  {"surah": "68", "name": "القلم", "revelationType": "مكية", "page": 564},
  {"surah": "69", "name": "الحاقة", "revelationType": "مكية", "page": 566},
  {"surah": "70", "name": "المعارج", "revelationType": "مكية", "page": 568},
  {"surah": "71", "name": "نوح", "revelationType": "مكية", "page": 570},
  {"surah": "72", "name": "الجن", "revelationType": "مكية", "page": 572},
  {"surah": "73", "name": "المزمل", "revelationType": "مكية", "page": 574},
  {"surah": "74", "name": "المدثر", "revelationType": "مكية", "page": 575},
  {"surah": "75", "name": "القيامة", "revelationType": "مكية", "page": 577},
  {"surah": "76", "name": "الانسان", "revelationType": "مدنية", "page": 578},
  {"surah": "77", "name": "المرسلات", "revelationType": "مكية", "page": 580},
  {"surah": "78", "name": "النبإ", "revelationType": "مكية", "page": 582},
  {"surah": "79", "name": "النازعات", "revelationType": "مكية", "page": 583},
  {"surah": "80", "name": "عبس", "revelationType": "مكية", "page": 585},
  {"surah": "81", "name": "التكوير", "revelationType": "مكية", "page": 586},
  {"surah": "82", "name": "الإنفطار", "revelationType": "مكية", "page": 587},
  {"surah": "83", "name": "المطففين", "revelationType": "مكية", "page": 588},
  {"surah": "84", "name": "الإنشقاق", "revelationType": "مكية", "page": 589},
  {"surah": "85", "name": "البروج", "revelationType": "مكية", "page": 590},
  {"surah": "86", "name": "الطارق", "revelationType": "مكية", "page": 591},
  {"surah": "87", "name": "الأعلى", "revelationType": "مكية", "page": 591},
  {"surah": "88", "name": "الغاشية", "revelationType": "مكية", "page": 592},
  {"surah": "89", "name": "الفجر", "revelationType": "مكية", "page": 593},
  {"surah": "90", "name": "البلد", "revelationType": "مكية", "page": 594},
  {"surah": "91", "name": "الشمس", "revelationType": "مدنية", "page": 595},
  {"surah": "92", "name": "الليل", "revelationType": "مدنية", "page": 595},
  {"surah": "93", "name": "الضحى", "revelationType": "مكية", "page": 596},
  {"surah": "94", "name": "الشرح", "revelationType": "مكية", "page": 596},
  {"surah": "95", "name": "التين", "revelationType": "مكية", "page": 597},
  {"surah": "96", "name": "العلق", "revelationType": "مكية", "page": 597},
  {"surah": "97", "name": "القدر", "revelationType": "مكية", "page": 598},
  {"surah": "98", "name": "البينة", "revelationType": "مدنية", "page": 598},
  {"surah": "99", "name": "الزلزلة", "revelationType": "مدنية", "page": 599},
  {"surah": "100", "name": "العاديات", "revelationType": "مكية", "page": 599},
  {"surah": "101", "name": "القارعة", "revelationType": "مكية", "page": 600},
  {"surah": "102", "name": "التكاثر", "revelationType": "مكية", "page": 600},
  {"surah": "103", "name": "العصر", "revelationType": "مكية", "page": 601},
  {"surah": "104", "name": "الهمزة", "revelationType": "مكية", "page": 601},
  {"surah": "105", "name": "الفيل", "revelationType": "مكية", "page": 601},
  {"surah": "106", "name": "قريش", "revelationType": "مكية", "page": 602},
  {"surah": "107", "name": "الماعون", "revelationType": "مكية", "page": 602},
  {"surah": "108", "name": "الكوثر", "revelationType": "مكية", "page": 602},
  {"surah": "109", "name": "الكافرون", "revelationType": "مكية", "page": 603},
  {"surah": "110", "name": "النصر", "revelationType": "مدنية", "page": 603},
  {"surah": "111", "name": "المسد", "revelationType": "مكية", "page": 603},
  {"surah": "112", "name": "الإخلاص", "revelationType": "مكية", "page": 604},
  {"surah": "113", "name": "الفلق", "revelationType": "مكية", "page": 604},
  {"surah": "114", "name": "الناس", "revelationType": "مكية", "page": 604}
];

List<int> noOfVerses = [
  7,
  286,
  200,
  176,
  120,
  165,
  206,
  75,
  129,
  109,
  123,
  111,
  43,
  52,
  99,
  128,
  111,
  110,
  98,
  135,
  112,
  78,
  118,
  64,
  77,
  227,
  93,
  88,
  69,
  60,
  34,
  30,
  73,
  54,
  45,
  83,
  182,
  88,
  75,
  85,
  54,
  53,
  89,
  59,
  37,
  35,
  38,
  29,
  18,
  45,
  60,
  49,
  62,
  55,
  78,
  96,
  29,
  22,
  24,
  13,
  14,
  11,
  11,
  18,
  12,
  12,
  30,
  52,
  52,
  44,
  28,
  28,
  20,
  56,
  40,
  31,
  50,
  40,
  46,
  42,
  29,
  19,
  36,
  25,
  22,
  17,
  19,
  26,
  30,
  20,
  15,
  21,
  11,
  8,
  8,
  19,
  5,
  8,
  8,
  11,
  11,
  8,
  3,
  9,
  5,
  4,
  7,
  3,
  6,
  3,
  5,
  4,
  5,
  6
];
